<?php
namespace Echo_Doc_Blocks\Includes;

use Echo_Doc_Blocks\Includes\features\templates\Templates_Setup;
use Echo_Doc_Blocks\Includes\Features\Dynamic\KB_Recent_Articles;
use Echo_Doc_Blocks\Includes\Features\Dynamic\KB_Categories;
use Echo_Doc_Blocks\Includes\Features\Dynamic\KB;
use Echo_Doc_Blocks\Includes\Utilities;
use Echo_Doc_Blocks\Includes\kb\KB_Utilities;

defined( 'ABSPATH' ) || exit();

class Assets_Manager {

	public static function init() {

        add_filter( 'block_categories', [ __CLASS__, 'register_block_category'], 10, 2 );

        add_action( 'enqueue_block_assets', [ __CLASS__, 'block_assets' ] );

        // backend JS and CSS
        add_action( 'enqueue_block_editor_assets', [ __CLASS__, 'epbl_block_editor_assets' ] );
		
		// Register Dynamic Blocks 
		new KB_Recent_Articles();
		new KB_Categories();
		new KB();
	}

    // Add our custom block category
    static function register_block_category( $categories, $post ) {
        return array_merge(
            $categories,
            array(
                array(
                    'slug'  => 'echo-document-blocks',
                    'title' => __( 'Blocks for Documents and FAQs', 'echo-document-blocks' ),
                ),
            )
        );
    }

    /**
     * FRONTEND and BACKEND JavaScript and CSS
     */
    static function block_assets() {

        // in FRONT END do not load JS and CSS if no EPBL blocks are present
        if ( ( is_admin() && ! get_current_screen()->is_block_editor() ) || ( ! is_admin() && false === Templates_Setup::$found_epbl_blocks ) ) {
            return;
        }

        // CSS + JS for blocks FRONTEND and BACKEND
        wp_enqueue_style( 'epbl-blocks-css', ECHO_BLOCKS_ASSETS_URL . 'css/blocks.style.css', array(), ECHO_BLOCKS_VERSION);
    }

    /**
     * ADMIN BACKEND - EDITOR JavaScript and CSS
     */
    static function epbl_block_editor_assets() {

        // JS for all blocks, generated by Webpack
        wp_enqueue_script( 'epbl-blocks-editor-js', ECHO_BLOCKS_ASSETS_URL . 'js/editor.blocks.js',
            array( 'wp-blocks', 'wp-i18n', 'wp-element', 'wp-components', 'wp-editor', 'wp-edit-post', 'wp-api', 'jquery', 'jquery-ui-core','jquery-ui-dialog' ),
            ECHO_BLOCKS_VERSION,
            true // Enqueue the script in the footer
        );
		
		$epbl_blocks_configuration = array(
            'tablet_breakpoint' => ECHO_BLOCKS_TABLET_BREAKPOINT,
            'mobile_breakpoint' => ECHO_BLOCKS_MOBILE_BREAKPOINT,
            'ajax_nonce'        => wp_create_nonce( 'epbl-templates-mgr-nonce' ),
			'kbChoices'         => array()
        );
		
		if ( Utilities::is_kb_plugin_active() ) {
			$kb_configs = KB_Utilities::get_kb_configs();
			if ( count( $kb_configs ) ) {
				foreach ( $kb_configs as $config ) {
					$epbl_blocks_configuration['kbChoices'][] = array(
						'label' => $config['kb_name'],
						'value' => $config['id']
					);
				}
			}
		}
		
        wp_localize_script(	'epbl-blocks-editor-js', 'epbl_blocks_configuration', $epbl_blocks_configuration );

        // CSS for all blocks styles, generated by Webpack
        wp_enqueue_style( 'epbl-blocks-editor-css',	ECHO_BLOCKS_ASSETS_URL . 'css/blocks.editor.css',	array( 'wp-edit-blocks' ),	ECHO_BLOCKS_VERSION);
    }

    /**
     * ADMIN BACKEND - PLUGIN PAGES (Getting Started, Plugin settings, reports, lists etc.)
     */
    function load_admin_plugin_pages_resources() {

        // if SCRIPT_DEBUG is off then use minified scripts
        $suffix = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';

        // JS and CSS for Admin plugin pages OTHER THAN Template Manager
        wp_enqueue_style( 'epbl-admin-plugin-pages-styles', ECHO_BLOCKS_ASSETS_URL . 'css/admin-plugin-pages' . $suffix . '.css', array(), ECHO_BLOCKS_VERSION );
        wp_enqueue_script( 'epbl-admin-plugin-pages-scripts', ECHO_BLOCKS_ASSETS_URL . 'js/admin-plugin-pages' . $suffix . '.js',
            array( 'jquery', 'jquery-ui-core', 'jquery-ui-dialog', 'jquery-effects-core'), ECHO_BLOCKS_VERSION );
        wp_localize_script( 'epbl-admin-plugin-pages-scripts', 'epbl_vars', array(
            'ajaxurl' => admin_url( 'admin-ajax.php' ),
            'msg_try_again' => esc_html__( 'Please try again later.', 'blocks-for-documents-articles-and-faqs' ),
            'error_occurred' => esc_html__( 'Error occurred (11)', 'blocks-for-documents-articles-and-faqs' ),
            'not_saved' => esc_html__( 'Error occurred - configuration NOT saved (12).', 'blocks-for-documents-articles-and-faqs' ),
            'unknown_error' => esc_html__( 'unknown error (13)', 'blocks-for-documents-articles-and-faqs' ),
            'reload_try_again' => esc_html__( 'Please reload the page and try again.', 'blocks-for-documents-articles-and-faqs' ),
            'save_config' => esc_html__( 'Saving configuration', 'blocks-for-documents-articles-and-faqs' ),
            'input_required' => esc_html__( 'Input is required', 'blocks-for-documents-articles-and-faqs' ),
        ) );
    }

    /**
     * ADMIN BACKEND - TEMPLATE MANAGER
     */
    function load_admin_template_manager() {

        // if SCRIPT_DEBUG is off then use minified scripts
        $suffix = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';

        // JS and CSS for Template Manager
        wp_enqueue_style( 'epbl-template-manager-css', ECHO_BLOCKS_ASSETS_URL . 'css/admin-template-manager.css' );
        wp_enqueue_script( 'epbl-admin-template-manager-scripts', ECHO_BLOCKS_ASSETS_URL . 'js/admin-template-manager' . $suffix . '.js',
            array('jquery',	'jquery-ui-core', 'jquery-ui-dialog', 'jquery-effects-core'), ECHO_BLOCKS_VERSION );
        wp_localize_script( 'epbl-admin-template-manager-scripts', 'epbl_vars', array(
            'ajaxurl' => admin_url( 'admin-ajax.php' ),
            'msg_try_again' => esc_html__( 'Please try again later.', 'blocks-for-documents-articles-and-faqs' ),
            'error_occurred' => esc_html__( 'Error occurred (11)', 'blocks-for-documents-articles-and-faqs' ),
            'not_saved' => esc_html__( 'Error occurred - configuration NOT saved (12).', 'blocks-for-documents-articles-and-faqs' ),
            'unknown_error' => esc_html__( 'unknown error (13)', 'blocks-for-documents-articles-and-faqs' ),
            'reload_try_again' => esc_html__( 'Please reload the page and try again.', 'blocks-for-documents-articles-and-faqs' ),
            'save_config' => esc_html__( 'Saving configuration', 'blocks-for-documents-articles-and-faqs' ),
            'input_required' => esc_html__( 'Input is required', 'blocks-for-documents-articles-and-faqs' )
        ) );
    }

    /**
     * ADMIN BACKEND - TEMPLATE EDITOR
     *
     * @param $classes
     * @return string
     */
    function load_admin_template_editor( $classes ) {
        return $classes . ' epbl-template-editor-body ';
    }
}
